
package localhost._8080.md5;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MD5Impl", targetNamespace = "http://localhost:8080/MD5")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MD5Impl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "MD5")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "MD5", targetNamespace = "http://localhost:8080/MD5", className = "localhost._8080.md5.MD5")
    @ResponseWrapper(localName = "MD5Response", targetNamespace = "http://localhost:8080/MD5", className = "localhost._8080.md5.MD5Response")
    @Action(input = "http://localhost:8080/MD5/MD5Impl/MD5Request", output = "http://localhost:8080/MD5/MD5Impl/MD5Response", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://localhost:8080/MD5/MD5Impl/MD5/Fault/Exception")
    })
    public String md5(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

}
