/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PRINT_SERVICE_H_RPCGEN
#define _PRINT_SERVICE_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MAX_SIZE 100000

#define EXERCISE3 666
#define EX_3_VERSION_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define printString 1
extern  enum clnt_stat printstring_1(char **, void *, CLIENT *);
extern  bool_t printstring_1_svc(char **, void *, struct svc_req *);
extern int exercise3_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define printString 1
extern  enum clnt_stat printstring_1();
extern  bool_t printstring_1_svc();
extern int exercise3_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PRINT_SERVICE_H_RPCGEN */
