/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "print_service.h"

bool_t
printstring_1_svc(char **argp, void *result, struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	printf("Received string: %s\n", *argp);

	return retval;
}

int
exercise3_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
