/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "print_service.h"
#include <sys/time.h>

#define NUM_ITERATIONS	100


void
exercise3_1(char *host)
{
	CLIENT *clnt;
	int sizes[] = {10, 100, 200, 500, 1000, 2000, 5000, 10000, 15000, 20000, 100000};
	struct timeval t1;
	struct timeval t2;


#ifndef	DEBUG
	clnt = clnt_create (host, EXERCISE3, EX_3_VERSION_1, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int i;
	int k;
	int n;
	int length = sizeof(sizes)/sizeof(sizes[1]);
	for(i = 0; i < length; i++){
		k = sizes[i];
		char *string = calloc(k, sizeof(char));
		memset(string, '1', k);
		gettimeofday(&t1, NULL);
		unsigned long long time1 =
			    (unsigned long long)(t1.tv_sec) * 1000000 +
			    (unsigned long long)(t1.tv_usec);
		for(n = 0; n < NUM_ITERATIONS; n++){
			printstring_1(&string, NULL, clnt);
		}
		gettimeofday(&t2, NULL);
		unsigned long long time2 =
			    (unsigned long long)(t2.tv_sec) * 1000000 +
			    (unsigned long long)(t2.tv_usec);

		unsigned long long avg_time = (time2-time1)/NUM_ITERATIONS;
		printf("Time for size %d: %llu\n", k, avg_time);
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host string\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	exercise3_1 (host);
exit (0);
}
