#define MAX_COMMAND 	11

/* Mutex & Threads */
pthread_mutex_t socket_mtx;
pthread_mutex_t users_list_mtx;
pthread_t thread;
pthread_attr_t thread_att;
/* Controls the access to the socket generated by the connection 'accept' */
pthread_cond_t free_socket;
pthread_cond_t free_list;

/* Variable that controls the state of the socket created by the connection 'accept' */
int busy_socket;

/* Declare the list of users */
struct user *users;

void interruptHandler(int sig);
void * manageRequest(int *sd);
void toUpperCase(char * string);