
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PrintString", targetNamespace = "http://ws.server/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PrintString {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://ws.server/PrintString/printStrRequest", output = "http://ws.server/PrintString/printStrResponse")
    public void printStr(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
