
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PrintStringImplService", targetNamespace = "http://ws.server/", wsdlLocation = "http://127.0.1.1:8080/ws/printString?wsdl")
public class PrintStringImplService
    extends Service
{

    private final static URL PRINTSTRINGIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRINTSTRINGIMPLSERVICE_EXCEPTION;
    private final static QName PRINTSTRINGIMPLSERVICE_QNAME = new QName("http://ws.server/", "PrintStringImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.1.1:8080/ws/printString?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRINTSTRINGIMPLSERVICE_WSDL_LOCATION = url;
        PRINTSTRINGIMPLSERVICE_EXCEPTION = e;
    }

    public PrintStringImplService() {
        super(__getWsdlLocation(), PRINTSTRINGIMPLSERVICE_QNAME);
    }

    public PrintStringImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRINTSTRINGIMPLSERVICE_QNAME, features);
    }

    public PrintStringImplService(URL wsdlLocation) {
        super(wsdlLocation, PRINTSTRINGIMPLSERVICE_QNAME);
    }

    public PrintStringImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRINTSTRINGIMPLSERVICE_QNAME, features);
    }

    public PrintStringImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrintStringImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PrintString
     */
    @WebEndpoint(name = "PrintStringImplPort")
    public PrintString getPrintStringImplPort() {
        return super.getPort(new QName("http://ws.server/", "PrintStringImplPort"), PrintString.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrintString
     */
    @WebEndpoint(name = "PrintStringImplPort")
    public PrintString getPrintStringImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.server/", "PrintStringImplPort"), PrintString.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRINTSTRINGIMPLSERVICE_EXCEPTION!= null) {
            throw PRINTSTRINGIMPLSERVICE_EXCEPTION;
        }
        return PRINTSTRINGIMPLSERVICE_WSDL_LOCATION;
    }

}
